{{- if .Values.temporal.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-temporal
  labels:
    app: temporal
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.temporal.replicas }}
  selector:
    matchLabels:
      app: temporal
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: temporal
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: temporal
          image: "{{ .Values.temporal.image.repository }}:{{ .Values.temporal.image.tag }}"
          ports:
            - containerPort: 7233
              name: grpc
            - containerPort: 7234
            - containerPort: 7235
            - containerPort: 7239
              name: metrics
          env:
            - name: DB
              value: postgres12
            - name: DB_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PWD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgresql
                  key: postgres-password
            - name: POSTGRES_SEEDS
              value: {{ .Release.Name }}-postgresql
          resources:
            {{- toYaml .Values.temporal.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-temporal
  labels:
    app: temporal
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.temporal.service.type }}
  ports:
    - name: grpc
      port: {{ .Values.temporal.service.port }}
      targetPort: 7233
    - name: metrics
      port: 9090
      targetPort: 7239
  selector:
    app: temporal
    release: {{ .Release.Name }}
{{- end }}
