global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "temporal"
    static_configs:
      - targets: ["temporal-server:9090"]
    metrics_path: /metrics

  - job_name: "billing-service"
    static_configs:
      - targets: ["host.docker.internal:8082"]
    metrics_path: /metrics

  - job_name: "usage-collector"
    static_configs:
      - targets: ["host.docker.internal:8083"]
    metrics_path: /metrics
